# Site settings
title: Xmartlabs Blog
email: getintouch@xmartlabs.com
address: Bulevar España 2529 - 11300
phone_eeuu: +16506141829
phone_uruguay: (+598) 2408 7915
description: > # this means to ignore newlines until "baseurl:"
  Articles by Xmartlabs, sharing the knowledge about full-stack mobile design and development in iOS, Android and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: 'https://xmartlabs.com'
url_team: 'https://xmartlabs.com/#our_team'
url_blog: 'https://blog.xmartlabs.com'
twitter_username: xmartlabs
github_username: xmartlabs

jekyll-crosspost_to_medium:
  status: draft
  backdate: true
  license: all-rights-reserved
#   text: '<p><i>Your (optional) signoff for the post.</i></p>',

# Build settings
markdown: kramdown
future: false
timezone: America/Montevideo
permalink: /:year/:month/:day/:title/

# sass:
#   style: :compressed

defaults:
  # Default layout and language to everything
  -
    values:
      layout: "default"
  # Specify default pages’ layout
  -
    scope:
      path: "_posts/martin"
      type: "posts"
    values:
      author: "mtnBarreto"

exclude:
  - README.md
  - vendor/
  - docker-compose.yml
