name: CI
on: push
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install RVM
      run: curl -sSL https://get.rvm.io | bash
    - name: Install Ruby
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version) --binary
        rvm --default use $(cat .ruby-version)
    - name: Install Bundler
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler
    - name: Install Ruby dependencies
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle install
    - name: Build Jekyll
      run: |
        source $HOME/.rvm/scripts/rvm
        jekyll build --trace --strict_front_matter
    - name: Check HTML
      run: |
        source $HOME/.rvm/scripts/rvm
        htmlproofer --empty-alt-ignore --allow_hash_href --disable_external _site/
