name: Compile and check blog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll
      uses: jerryjvl/jekyll-build-action@v1
    - name: Check HTML
      uses: chabad360/htmlproofer@v1.1
      with:
        directory: "_site/"
        arguments: --empty-alt-ignore --allow_hash_href --disable_external
